<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <RootNamespace>Microsoft.Iris.DebugAdapter.Server</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="OmniSharp.Extensions.DebugAdapter.Server" Version="0.19.9" />
        <ProjectReference Include="..\..\libs\MicrosoftIris\UIX\UIX.csproj" />
        <ProjectReference Include="..\UIX.DebugAdapter.Shared\UIX.DebugAdapter.Shared.csproj" />
        
        <PackageReference Include="PolySharp" Version="1.15.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>
